server:
  port: 9009
spring:
  application:
    name: huahua-sms #指定服务名
  rabbitmq:
    host: 39.97.117.83
    username: guest
    password: zhangyy


#短信发送的参数模板
api:
  send:
    appCode: 1700bd3f5847403fbe29e5ded27be5d2
    tplid: TP18040315
