server: 
  port: 9005
spring: 
  application:  
    name: huahua-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.117.83:3306/huahua_gathering?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true

  redis:
    host: 39.97.117.83
    port: 6379
